import PDFDocument from "pdfkit";
import { type ITrip } from "../models/trip.model";
import type { Response } from "express";

const PDFService = {
  generateTripWorkOrder: (trip: ITrip, res: Response) => {
    const doc = new PDFDocument({ margin: 50 });

    const filename = `WorkOrder-${trip.tripNumber}.pdf`;

    res.setHeader("Content-disposition", `attachment; filename="${filename}"`);
    res.setHeader("Content-type", "application/pdf");

    doc.pipe(res);

    // Header
    doc.fontSize(20).text("Work Order / Trip Summary", { align: "center" });
    doc.moveDown();

    // Trip Details
    doc.fontSize(14).text(`Trip Reference: # ${trip.tripNumber}`);
    doc.moveDown();

    doc.fontSize(12).text(`Status: ${trip.status.toUpperCase()}`);
    doc.text(
      `Scheduled Date: ${new Date(trip.scheduledDate).toLocaleDateString()}`,
    );
    doc.moveDown();

    // Route
    doc.fontSize(14).text("Route Information", { underline: true });
    doc.fontSize(12).text(`From: ${trip.startLocation}`);
    doc.text(`To: ${trip.endLocation}`);

    if (trip.estimatedDistance) {
      doc.text(`Estimated Distance: ${trip.estimatedDistance} km`);
    }
    doc.moveDown();

    // Resources
    doc.fontSize(14).text("Assigned Resources", { underline: true });
    // Handle populated fields safely
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const driverName = (trip.driver as any).name || "Unknown";
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const driverEmail = (trip.driver as any).email || "";

    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const truckParams = trip.truck
      ? `${(trip.truck as any).licensePlate} (${(trip.truck as any).brand})`
      : "None";
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const trailerParams = trip.trailer
      ? `${(trip.trailer as any).licensePlate} (${(trip.trailer as any).type})`
      : "None";

    doc.fontSize(12).text(`Driver: ${driverName} (${driverEmail})`);
    doc.text(`Truck: ${truckParams}`);
    doc.text(`Trailer: ${trailerParams}`);
    doc.moveDown();

    // Operational Data (if available)
    if (trip.status !== "planned") {
      doc.fontSize(14).text("Operational Data", { underline: true });

      if (trip.startDate) {
        doc
          .fontSize(12)
          .text(`Start Time: ${new Date(trip.startDate).toLocaleString()}`);
        doc.text(`Start Mileage: ${trip.startMileage || 0} km`);
      }

      if (trip.endDate) {
        doc.text(`End Time: ${new Date(trip.endDate).toLocaleString()}`);
        doc.text(`End Mileage: ${trip.endMileage || 0} km`);
        doc.text(`Actual Distance: ${trip.actualDistance || 0} km`);
        doc.text(`Fuel Added: ${trip.fuelAdded || 0} Liters`);
      }
    }

    // Notes
    if (trip.notes) {
      doc.moveDown();
      doc.fontSize(14).text("Notes", { underline: true });
      doc.fontSize(12).text(trip.notes);
    }

    // Footer
    doc.moveDown(2);
    doc
      .fontSize(10)
      .text("Generated by CamYou Fleet Manager", {
        align: "center",
        textIndent: 20,
      });

    doc.end();
  },
};

export default PDFService;
